// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  14

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    eleccions_a_delegat
    (
        init => init
        upgrade => upgrade
        fund => fund
        claim => claim
        setMaxDepositPerWallet => set_max_deposit_per_donor
        status => status
        getCurrentFunds => get_current_funds
        getTarget => target
        getDeadline => deadline
        getMinFund => min_fund
        getMaxDepositPerDonor => max_deposit_per_donor
        getMaxTarget => max_target
        getDeposit => deposit
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
